Format updates to shell scripts

diff --git a/bin/functions b/bin/functions
--- a/bin/functions
+++ b/bin/functions
@@ -9,16 +9,16 @@ log-warning() {
 fatal() {
   local status_code=1
   while [[ "${1:-}" == -* ]]; do
-    case "${1:-}" in
+  case "${1:-}" in
       -s|--status-code)
-        status_code="${2:-1}"
-        shift 2
-        ;;
+    status_code="${2:-1}"
+    shift 2
+    ;;
       *)
-        echo "[FATAL] Unknown option to fatal function: ${1:-}" >&2
-        exit 1
-        ;;
-    esac
+    echo "[FATAL] Unknown option to fatal function: ${1:-}" >&2
+    exit 1
+    ;;
+  esac
   done
 
   echo "[FATAL] $*" >&2
@@ -45,6 +45,6 @@ read-file-or-die() {
   local status_code="${2:-1}"
 
   if ! cat "$target_file" 2>/dev/null; then
-    fatal -s "$status_code" "Failed to read [$target_file]"
+  fatal -s "$status_code" "Failed to read [$target_file]"
   fi
 }
